#!/bin/bash

echo "=================================================="
echo "ACCESS YOUR DEMOS - DNS ISSUE WORKAROUND"
echo "=================================================="
echo ""
echo "The issue: rootuip.com points to the wrong server!"
echo ""
echo "SOLUTION 1 - Update your computer's hosts file:"
echo "=================================================="
echo "Add this line to your hosts file:"
echo "24.44.95.254 rootuip.com www.rootuip.com app.rootuip.com"
echo ""
echo "- Windows: C:\\Windows\\System32\\drivers\\etc\\hosts"
echo "- Mac/Linux: /etc/hosts"
echo ""
echo "Then access:"
echo "- https://rootuip.com/ml-demo.html"
echo "- https://rootuip.com/login.html"
echo "- https://rootuip.com/enterprise-security-dashboard.html"
echo ""
echo "SOLUTION 2 - Direct IP Access (HTTP only):"
echo "=================================================="
echo "Access directly via IP address:"
echo "- http://24.44.95.254/ml-demo.html"
echo "- http://24.44.95.254/login.html"
echo "- http://24.44.95.254/enterprise-security-dashboard.html"
echo "- http://24.44.95.254/monitoring-dashboard.html"
echo "- http://24.44.95.254/simple-login.html"
echo ""
echo "API Endpoints via IP:"
echo "- http://24.44.95.254/ml/health"
echo "- http://24.44.95.254/auth/health"
echo ""
echo "SOLUTION 3 - SSH Port Forwarding:"
echo "=================================================="
echo "From your local computer, run:"
echo "ssh -L 8080:localhost:80 iii@24.44.95.254"
echo ""
echo "Then access:"
echo "- http://localhost:8080/ml-demo.html"
echo "- http://localhost:8080/login.html"
echo ""
echo "Current Service Status:"
echo "=================================================="
pm2 list | grep -E "name|demo|auth|ml-system|static-server"
echo ""
echo "Testing local access:"
echo -n "ML Demo: "
curl -s -o /dev/null -w "%{http_code}\n" http://localhost/ml-demo.html
echo -n "Login: "
curl -s -o /dev/null -w "%{http_code}\n" http://localhost/login.html
echo -n "ML API: "
curl -s http://localhost:3004/ml/health | grep -o '"status":"[^"]*"' || echo "Not accessible"
echo -n "Auth API: "
curl -s http://localhost:3003/auth/health | grep -o '"status":"[^"]*"' || echo "Not accessible"