#!/bin/bash

echo "=============================================="
echo "DEPLOY TO YOUR VPS at 145.223.73.4"
echo "=============================================="
echo ""
echo "Your VPS (rootuip.com) is at: 145.223.73.4"
echo "This machine is: 24.44.95.254 (local development)"
echo ""
echo "To deploy everything to your VPS, run these commands:"
echo ""
echo "1. Create deployment package:"
echo "=============================================="
echo "cd /home/iii/ROOTUIP"
echo "tar -czf rootuip-ml-deployment.tar.gz \\"
echo "  ml-system/ \\"
echo "  ml-demo.html \\"
echo "  login.html \\"
echo "  simple-login.html \\"
echo "  enterprise-security-dashboard.html \\"
echo "  monitoring-dashboard.html \\"
echo "  auth-enterprise/ \\"
echo "  static-server.js \\"
echo "  package.json \\"
echo "  package-lock.json"
echo ""
echo "2. Copy to your VPS:"
echo "=============================================="
echo "scp rootuip-ml-deployment.tar.gz root@145.223.73.4:/root/"
echo ""
echo "3. SSH to your VPS and extract:"
echo "=============================================="
echo "ssh root@145.223.73.4"
echo "cd /root"
echo "tar -xzf rootuip-ml-deployment.tar.gz"
echo ""
echo "4. Install and start services on VPS:"
echo "=============================================="
echo "# Install dependencies"
echo "cd /root && npm install"
echo "cd /root/ml-system && npm install"
echo ""
echo "# Start services with PM2"
echo "pm2 start /root/ml-system/ml-server.js --name ml-system"
echo "pm2 start /root/auth-enterprise/simple-auth.js --name auth-service"
echo "pm2 start /root/static-server.js --name static-server"
echo "pm2 save"
echo ""
echo "5. Copy HTML files to nginx directory on VPS:"
echo "=============================================="
echo "cp /root/*.html /var/www/html/"
echo "# or wherever nginx serves files on your VPS"
echo ""
echo "6. Update nginx on VPS to proxy APIs:"
echo "=============================================="
echo "# Add to nginx config:"
echo "location /ml/ {"
echo "    proxy_pass http://localhost:3004/ml/;"
echo "}"
echo "location /auth/ {"
echo "    proxy_pass http://localhost:3003/auth/;"
echo "}"
echo ""
echo "Then reload nginx: nginx -s reload"
echo ""
echo "=============================================="
echo "Your files will then work at:"
echo "- https://rootuip.com/ml-demo.html"
echo "- https://rootuip.com/login.html"
echo "- etc."