#!/bin/bash

echo "==================================================="
echo "Fix app.rootuip.com 404 Errors - Instructions"
echo "==================================================="
echo ""
echo "The issue: app.rootuip.com is not configured in nginx"
echo ""
echo "To fix this, run these commands with sudo:"
echo ""
echo "1. First, check if you have SSL certificates:"
echo "   sudo ls -la /etc/letsencrypt/live/"
echo ""
echo "2. If you have certificates for rootuip.com, copy the nginx config:"
echo "   sudo cp /home/iii/ROOTUIP/app.rootuip.com.nginx /etc/nginx/sites-available/app.rootuip.com"
echo ""
echo "3. Enable the site:"
echo "   sudo ln -s /etc/nginx/sites-available/app.rootuip.com /etc/nginx/sites-enabled/"
echo ""
echo "4. Test the configuration:"
echo "   sudo nginx -t"
echo ""
echo "5. If test passes, reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "6. If you don't have SSL certificates, get them first:"
echo "   sudo certbot --nginx -d app.rootuip.com"
echo ""
echo "Alternative: Use the main domain instead"
echo "========================================="
echo "If you can't set up app.rootuip.com, access via:"
echo "- https://rootuip.com/ml-demo.html"
echo "- https://rootuip.com/login.html"
echo "- https://rootuip.com/enterprise-security-dashboard.html"
echo ""
echo "Current service status:"
echo "-----------------------"
pm2 list
echo ""
echo "Testing local services:"
echo "-----------------------"
echo -n "Static Server (3000): "
curl -s http://localhost:3000/health | grep -o '"status":"[^"]*"' || echo "Not responding"
echo -n "Auth Service (3003): "
curl -s http://localhost:3003/auth/health | grep -o '"status":"[^"]*"' || echo "Not responding"
echo -n "ML System (3004): "
curl -s http://localhost:3004/ml/health | grep -o '"status":"[^"]*"' || echo "Not responding"