#!/bin/bash

echo "=============================================="
echo "SETUP ROOTUIP.COM ON THIS SERVER"
echo "=============================================="
echo ""
echo "STEP 1: Update DNS Records"
echo "=============================================="
echo "Go to your DNS provider and update:"
echo "- A record for rootuip.com → 24.44.95.254"
echo "- A record for www.rootuip.com → 24.44.95.254"
echo "- A record for app.rootuip.com → 24.44.95.254"
echo ""
echo "Current DNS points to: 145.223.73.4 (WRONG SERVER)"
echo "This server IP: 24.44.95.254"
echo ""
echo "STEP 2: Get SSL Certificate (after DNS propagates)"
echo "=============================================="
echo "Run these commands:"
echo ""
echo "sudo certbot certonly --standalone -d rootuip.com -d www.rootuip.com -d app.rootuip.com"
echo ""
echo "STEP 3: Update Nginx Configuration"
echo "=============================================="
echo "sudo cp /home/iii/ROOTUIP/nginx-full-config.conf /etc/nginx/sites-available/default"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"
echo ""
echo "STEP 4: Test Everything"
echo "=============================================="
echo "Once DNS propagates and nginx is configured:"
echo "- https://rootuip.com/ml-demo.html"
echo "- https://rootuip.com/login.html"
echo "- https://rootuip.com/enterprise-security-dashboard.html"
echo ""
echo "TEMPORARY WORKAROUND (until DNS is fixed):"
echo "=============================================="
echo "Add to your computer's hosts file:"
echo "24.44.95.254 rootuip.com www.rootuip.com app.rootuip.com"
echo ""
echo "Location:"
echo "- Windows: C:\\Windows\\System32\\drivers\\etc\\hosts"
echo "- Mac/Linux: /etc/hosts"
echo ""
echo "Current Service Status:"
echo "=============================================="
pm2 list | grep -E "online|stopped"
echo ""
echo "All services are running and ready!"
echo "Just need to fix DNS and SSL certificate."