#!/bin/bash

echo "Setting up nginx configuration for app.rootuip.com"
echo "================================================="
echo ""
echo "Please run the following commands with sudo:"
echo ""
echo "1. Copy the nginx configuration file:"
echo "   sudo cp /home/iii/ROOTUIP/app.rootuip.com.nginx.conf /etc/nginx/sites-available/app.rootuip.com"
echo ""
echo "2. Enable the site by creating a symlink:"
echo "   sudo ln -s /etc/nginx/sites-available/app.rootuip.com /etc/nginx/sites-enabled/"
echo ""
echo "3. Test the nginx configuration:"
echo "   sudo nginx -t"
echo ""
echo "4. If the test passes, reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "5. Check the nginx status:"
echo "   sudo systemctl status nginx"
echo ""
echo "================================================="
echo ""
echo "Current services running:"
echo "- Port 3001: Next.js server (might need to be replaced with auth service)"
echo "- Port 3002: enterprise-auth-demo.js"
echo "- Port 3003: simple-auth.js"
echo "- Port 3004: Unknown service"
echo "- Port 3005: Not running (workflow service needed)"
echo ""
echo "To test after nginx setup:"
echo "- curl http://app.rootuip.com/"
echo "- curl http://app.rootuip.com/auth/health"
echo "- curl http://app.rootuip.com/integrations/health"