global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rootuip-prod'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rootuip-vps'

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # ROOTUIP Application Metrics
  - job_name: 'rootuip-app'
    static_configs:
      - targets: ['localhost:3003']
    metrics_path: '/metrics'

  # Auth Service Metrics
  - job_name: 'auth-service'
    static_configs:
      - targets: ['localhost:3002']
    metrics_path: '/api/metrics'

  # ML Service Metrics
  - job_name: 'ml-service'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/ml/metrics'

  # API Gateway Metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:3001']
    metrics_path: '/gateway/metrics'

  # Nginx Metrics (if nginx-prometheus-exporter is installed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']

  # Blackbox Exporter - Endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://rootuip.com
          - https://app.rootuip.com
          - https://app.rootuip.com/api/health
          - https://app.rootuip.com/ml/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115